name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/
        arduino-cli core update-index
        arduino-cli core install arduino:avr
        arduino-cli lib install "WiFi@3.2.1"
        arduino-cli lib install "LoRa@0.8.0"
        arduino-cli lib install "CRC32@2.0.0"
        arduino-cli lib install "NTPClient@3.2.1"

    - name: Build Google Test
      run: |
        mkdir -p /tmp/gtest
        cd /tmp/gtest
        cmake /usr/src/googletest
        make
        sudo mv lib/*.a /usr/lib

    - name: Configure project
      run: |
        mkdir build
        cd build
        cmake -D CMAKE_INCLUDE_DIRECTORIES_PROJECT_BEFORE=ON -D CMAKE_CXX_FLAGS="-I${{ github.workspace }}/src -I$HOME/Arduino/libraries" ..
        ls -la ${{ github.workspace }}/src

    - name: Build tests
      run: |
        cd build
        make VERBOSE=1

    - name: Run tests
      run: |
        cd build
        ./test_runner
